# Basic numpy 

Numpy is a python library used for working on arrays.
it  also has function for working in domain of linear algebra,fourier transform,and matrices.
numpy was created in 2005 by travis oliphant. it is an open source project and you can use it freely.
Numpy stands for numerical python


In [ ]:
The elements are all of same type , referred to as the array dtype
The rank of all the array is the number of dimensions .
The shape of the array is a tuple of integers giving the size of the array along each dimensions.


In [ ]:
1D array , 2D array , 3D array ,nd array ,vector , matix

In [ ]:
to create a basic array we use 

np.array() , np.zeros() , np.ones() , np.empty() , np.arange() , np.linspace() , dtype


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [3]:
np.shape(arr)

(5,)

In [8]:
print(np.zeros(2))

[0. 0.]


In [9]:
print(np.zeros([2,3]))            # 2 stands for rows and 3 stands for columns

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones([4,4]))          

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
print(np.empty(3))

[3.44899520e-307 3.44900369e-307 3.22646744e-307]


In [8]:
np.linspace(0,10,num=10)           # start from 0 and ends at 10 . and num = 10 -> number of values

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.linspace(11,58,num=10)

array([11.        , 16.22222222, 21.44444444, 26.66666667, 31.88888889,
       37.11111111, 42.33333333, 47.55555556, 52.77777778, 58.        ])

In [10]:
print(range(5))               # gives the range -> (0,5)
a = np.arange(15)             # similar to range but it gives the all the values in range from the starting point
a

range(0, 5)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [15]:
a = np.arange(15)               
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
range(6)

range(0, 6)

In [17]:
type(a)

numpy.ndarray

In [19]:
arr = np.array([1,2,3,4,5])

In [5]:
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
np.shape(arr2)

[[1 2 3 4 5]
 [1 2 3 4 5]]


(2, 5)

In [15]:
for i in range(6):
    print(i)

0
1
2
3
4
5


In [23]:
for i in np.arange(6):
    print(i)

0
1
2
3
4
5


In [9]:
b = np.array([[1,2,3,5],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  5],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
b[1:2][0]                        #slicing

array([5, 6, 7, 8])

In [11]:
b[1,1]                 # indexing starts from 0 

6

In [12]:
b[1][1]

6

In [26]:
b.shape               #function

(3, 4)

In [27]:
b[1][2]

7

In [28]:
b[2][3]

12

In [30]:
b[:3][2]

array([ 9, 10, 11, 12])

In [33]:
b[0:1][:3]

array([[1, 2, 3, 5]])

In [34]:
b[0:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [35]:
#more than one dimension
a = np.array([[1,2],[3,4],[6,80]])
print(a)

[[ 1  2]
 [ 3  4]
 [ 6 80]]


In [15]:
#minimum dimension

a= np.array([1,2,3,4,5],ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [16]:
a= np.array([1,2,3,4,5],ndmin = 2,dtype = complex)             #dtype is required for making a specially one datatype.
print(a)

[[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]]


In [13]:
a= np.array([1,2,3,4,5],ndmin = 2,dtype = int)
print(a)

[[1 2 3 4 5]]


In [14]:
a= np.array([1,2,3,4,5],ndmin = 2,dtype = float)
print(a)

[[1. 2. 3. 4. 5.]]


In [37]:
#dtype parameter

a = np.array([1,2,3],dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [17]:
#using array - scalar type

dt = np.dtype(np.int32)
print(dt)

int32


In [18]:
# int8, int16, int32, int64 can be replaced by equivalent string 'i1' , 'i2' , 'i4' , etc.

dt1 = np.dtype('i4')
print(dt1)

int32


In [40]:
#this resize the ndarray

import numpy as np

a= np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [41]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(6,1)
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [19]:
# an array of evenly spaced numbers

import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [45]:
#this is one diensional array
import numpy as np
a = np.arange(24)
print(a.ndim)

#now reshape it
b = a.reshape(2,3,4)            # 2 stands for two different arrays or matices and 3 stands for rows and 4 stands for columns
print(b)
b.shape
#b is having 3D

1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


(2, 3, 4)

In [46]:
#dtype of array is  int8(1 byte)

import numpy as np
x = np.array(b,dtype=np.int32)
print(x.itemsize)

4


In [47]:
import numpy as np
x = np.array(b,dtype=np.int64)
print(x.itemsize)

8


In [20]:
#dtype of array is float32( 4 byte)
import numpy as np
x = np.array(b,dtype=np.float32)
print(x.itemsize)

4


#adding removing and sorting the elements

np.sort() , np.concatenate()

In [21]:
arr = np.array([2,1,5,3,7,4,6,8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[5,2]])
np.concatenate((x,y), axis = 0)        #axis -> the directions along the rows and columns

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 2]])

In [27]:
np.concatenate((x,y) , axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 5, 2]])

Element-wise operation operator function
Addition + add()
subtraction - subtract()
multiplication * multiply()
division / divide()
exponentiation ** power()
mudulus % mod()

In [30]:
import numpy as np

first_array = np.array([1,3,5,7])
second_array = np.array([2,4,6,8])

#using the+ operator

result1 = first_array+second_array
print("using the + operator : ",result1)

#using the add() function
result2 = np.add(first_array , second_array)
print("using the add() function : ",result2)

using the + operator :  [ 3  7 11 15]
using the add() function :  [ 3  7 11 15]


In [32]:
#using the - operator

result1 = first_array-second_array
print("using the - operator : ",result1)

#using the subtract() function
result2 = np.subtract(first_array , second_array)
print("using the subtract() function : ",result2)


using the - operator :  [-1 -1 -1 -1]
using the subtract() function :  [-1 -1 -1 -1]


In [33]:
#using the * operator

result1 = first_array*second_array
print("using the * operator : ",result1)

#using the multiply() function
result2 = np.multiply(first_array , second_array)
print("using the multiply() function : ",result2)


using the * operator :  [ 2 12 30 56]
using the multiply() function :  [ 2 12 30 56]


In [34]:
#using the / operator

result1 = first_array/second_array
print("using the / operator : ",result1)

#using the divide() function
result2 = np.divide(first_array , second_array)
print("using the divide() function : ",result2)


using the / operator :  [0.5        0.75       0.83333333 0.875     ]
using the divide() function :  [0.5        0.75       0.83333333 0.875     ]


Array operations  --> functions
Array creation functions --> np.array(), np.zeros(), np.ones(), np.empty(), np.linspace(),etc
Array manipulation functions --> np.reshape(), np.transpose(),etc
Array mathematical functions -->  np.add(), np.subtract(), np.multiply(), np.divide(), etc
Array statistical functions --> np.mean(), np.median(), np.std(), np.var()
Array input and output functions --> np.save(), np.load(), np.loadtxt(), etc

In [49]:
first_array = np.array([1,3,5,7])
np.transpose(first_array,axes = 0)

print(first_array.transpose())

[1 3 5 7]


In [40]:
#task:  load the salaries.csv files,calculate the mean salary using np.mean()

import pandas as pd
salaries_df = pd.read_csv(r"C:\Users\Anish\Downloads\Salaries.csv")
np.mean(salaries_df['salary'])

108023.78205128205

In [41]:
np.median(salaries_df['salary'])            # in numpy we dont have mode function

104671.0

In [42]:
salaries_df['salary'].mode()

0    92000
Name: salary, dtype: int64

In [43]:
np.quantile(salaries_df['salary'],0.5)
q1 = np.quantile(salaries_df['salary'],0.25)
print(q1)

88612.5


In [44]:
q3 = np.quantile(salaries_df['salary'],0.75)
print(q3)

iqr = (q3-q1)/2
print(iqr)

[q3-1.5*iqr , q1+1.5*iqr]
min,max = q3-1.5*iqr , q1+1.5*iqr
iqrrange = [min,max]
iqrrange

126774.75
19081.125


[98153.0625, 117234.1875]

In [39]:
salaries_df['salary'].describe()

count        78.000000
mean     108023.782051
std       28293.661022
min       57800.000000
25%       88612.500000
50%      104671.000000
75%      126774.750000
max      186960.000000
Name: salary, dtype: float64

In [46]:
salaries_df[(salaries_df['salary']>min) & (salaries_df['salary']<max)].describe()

phd    service         salary
count  19.000000  19.000000      19.000000
mean   20.052632  13.000000  106367.526316
std     7.523841   8.034647    4062.946268
min     9.000000   0.000000   99418.000000
25%    13.500000   7.000000  103681.500000
50%    19.000000  10.000000  105000.000000
75%    25.000000  17.500000  109648.000000
max    35.000000  31.000000  116450.000000

Save the data in numpy

In [5]:
import numpy as np

#create an array 
array1 = np.array([[1,3,5],[2,4,6]])

#save the array to a text file
np.savetxt('data.txt',array1)


In [9]:
#load the data from the text file
loaded_data = np.loadtxt('data.txt')          #loadtxt is a function to load the data whichever data is present in the file

#print the loaded data
print(loaded_data)

[[1. 3. 5.]
 [2. 4. 6.]]


Operator descrption

<(less than)
<= (less than or equals to)
>(greater than)
>=(greater than or equals to)
==(equals to)
!=(not equals to)

In [10]:
import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([3,2,1])

#less than operator
result1 = array1 < array2
print("array1 < array2 :" , result1)        #output :[True FAlse False]

#greater than operator
result2 = array1 > array2
print("array1 > array2 :" , result2)    # output:[False False True]

#equals to operator
result3 = array1 == array2
print("array1 == array2 :" , result3)         #output:[False True False]

array1 < array2 : [ True False False]
array1 > array2 : [False False  True]
array1 == array2 : [False  True False]


Operator descrption

less()
less_equal()
greater()
greater_equal()
equal()
not_equal()

In [11]:
import numpy as np

array1 = np.array([9,12,21])
array2 = np.array([21,12,9])


#use of less()
result = np.less(array1,array2)
print("using the less()",result)

#use of less_equal()
result = np.less_equal(array1,array2)
print("using the less_equal()",result)

#use of greater()
result = np.greater(array1,array2)
print("using the greater()",result)

#use of greater_equal()
result = np.greater_equal(array1,array2)
print("using the greater_equal()",result)

#use of equal()
result = np.equal(array1,array2)
print("using the equal()",result)





using the less() [ True False False]
using the less_equal() [ True  True False]
using the greater() [False False  True]
using the greater_equal() [False  True  True]
using the equal() [False  True False]


operator description

logical_and  ->  computes the elements wise truth value of x1 AND x2
logical_or  ->  computes the elements wise truth value of x1 OR x2
logical_not  ->  computes the elements wise truth value of x1 NOT x2

In [12]:
import numpy as np

x1 = np.array([True,False,True])
x2 = np.array([False,False,True])

#logical AND
print(np.logical_and(x1,x2))

#logical OR
print(np.logical_or(x1,x2))

#logical NOT
print(np.logical_not(x1))

[False False  True]
[ True False  True]
[False  True False]


Trignometry Function --> computes(in radians)

sin() -> the sine of an angle
cos()  -> the cosine of an angle
tan() -> tangent of an angle
arcsin() -> the inverse sin
arccos() -> the inverse of cosin
arctan()  -> the inverse of tangent
degree() -> converts an angle in radians to degree
radians() -> converts an angle in degree to radians

In [13]:
import numpy as np

#array of angles in radians
angles = np.array([0,1,2])

#compute the sine of the angles
sine_values = np.sin(angles)
print("sine values :",sine_values)

#compute the inverse of the angles
inverse_sine = np.arcsin(angles)
print(" inverse sine values :", inverse_sine)


sine values : [0.         0.84147098 0.90929743]
 inverse sine values : [0.         1.57079633        nan]


C:\Users\Anish\AppData\Local\Temp\ipykernel_9296\93628105.py:11: RuntimeWarning: invalid value encountered in arcsin
  inverse_sine = np.arcsin(angles)


In [15]:
import numpy as np

#deefine the angle in radian
angle = 1.570796
print("initial angle in radian")

#convert the angle to degree
angle_degree = np.degrees(angle)

#convert the angle back to radians
angle_radian = np.radians(angle_degree)
print("angle in radians (after conversion:)",angle_radian)

initial angle in radian
angle in radians (after conversion:) 1.570796


rounding function

round() -> returns the value rounded to a desired precision 
floor() -> returns the values of aray down to the nearest integer that is less than each element 
ceil() -> returns the values of arrsy up to the nearest integer that is greater than each element .

In [1]:
import numpy as np

numbers = np.array([1.23456 , 3.45678 , 4.56789])

#round the array to the two decimal places
rounded_array = np.round(numbers,2)

print(rounded_array)

#output: [1.23 3.45 4.57]

import numpy as np

array1 = np.array([1.23456 , 3.45678 , 4.56789])
print("array after floor() : ", np.floor(array1))
print("array after ceil : " ,np.ceil(array1))

[1.23 3.46 4.57]
array after floor() :  [1. 3. 4.]
array after ceil :  [2. 4. 5.]


Numpy constants
In Numpy, the most commomly used constants are pi and e

In [3]:
import numpy as np

radius = 2
circumference = 2*np.pi*radius
print(circumference)

import numpy as np

y = np.e

print(y)
print(np.pi)

12.566370614359172
2.718281828459045
3.141592653589793


Statistical Function

functions  -> description
median() -> returns the median of an array
mean() -> returns the mean of an array
std() -> returns the standard deviation of an array
percentile() -> returns the nth percentile of elements in an array
min() -> retuns the minimum element of an array
max() -> returns the maximum element of an array




In [5]:
import numpy as np

#create a 1D array with 5 elements
array1 = np.array([1,2,3,4,5])

#calculate the median
median = np.median(array1)

#output: 3.0

import numpy as np

#create a 1D array with 6 elements
array1  = np.array([1,2,3,4,5,6])

#calculate the median
median = np.median(array1)
print(median)

#output: 3.5


3.5


In [7]:
import numpy as np

#create a 2D array
array1 = np.array([[2,4,5],
                  [8,10,12],
                  [14,26,18]])

#compute median along horizontal AXIS 
result1 = np.median(array1,axis=1)
print("median along horizontal axis :",result1)

#compute median along verical axis 
result2 = np.median(array1, axis=0)
print("median along verical axis:", result2)

#compute median of entire array
result3 = np.median(array1)
print("median of entire array:",result3)


median along horizontal axis : [ 4. 10. 18.]
median along verical axis: [ 8. 10. 12.]
median of entire array: 10.0


In [8]:
import numpy as np

#create a numpy array
marks = np.array([76,78,81,66,85])

#compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)


77.2


In [9]:
import numpy as np

#create a 2D array
array1 = np.array([[2,4,5],
                  [8,10,12],
                  [14,26,18]])
#compute a std along horizontal axis
result1 = np.std(array1 , axis=1)
print("std along horizontal axis :",result1)

#compute a std along a vertical axis
result2 = np.std(array1 , axis=0)
print("std along horizontal axis :",result2)

#compute std of entire array
result3 = np.std(array1)
print("std of entire array :",result3)


std along horizontal axis : [1.24721913 1.63299316 4.98887652]
std along horizontal axis : [4.89897949 9.28559218 5.31245915]
std of entire array : 7.1492035298424055


In [11]:
import numpy as np

#create an array
array1 = np.array([1,3,5,7,9,11,13,15,17])

#compute the 25th percentile of an array
result1 = np.percentile(array1,25)
print("25th percentile :",result1)

#compiute the 75th percentile of an array
result2 = np.percentile(array1,75)
print("75th percentile :",result2)
      
      

25th percentile : 5.0
75th percentile : 13.0


In [ ]:
String functions

functions -> description
add() -> comcatenates two strings
multiply() -> repeates a string for a specified number of times
capitalize() -> capitalizze the first letter of a string
lower() -> converts all upercase character in a string to lowercase
upper() -> converts all the lower case character in a string to upercase'
join() -> joins a sequence of strings
equals() -> checks if two strings are equal or not


In [12]:
import numpy as np

array1 = np.array(['iphone:','price:'])
array2 = np.array(['15','$900'])

#perform element wise array string concatenation
result = np.char.add(array1,array2)           #char is used to know that it is a string related data

print(result)


['iphone:15' 'price:$900']


In [13]:
import numpy as np

#define array with three string elements 
array1 = np.array(['A','B','C'])

#repeat each elements in array1 two times
result = np.char.multiply(array1,2)

print(result)

['AA' 'BB' 'CC']


In [14]:
import numpy as np

#define an array with three string elemets
array1 = np.array(['eric','paul','sean'])

#capitalize the first letter of each string in array1
result = np.char.capitalize(array1)

print(result)

['Eric' 'Paul' 'Sean']


In [15]:
import numpy as np

array1 = np.array(['nEaPali','AmeriCan','CaNadIan'])

#converts all string elements to uppercase
result1 = np.char.upper(array1)

#converts all strings elements to lowercase
result2 = np.char.lower(array1)

print("to uppercase: ",result1)
print("to lowercase:",result2)

to uppercase:  ['NEAPALI' 'AMERICAN' 'CANADIAN']
to lowercase: ['neapali' 'american' 'canadian']


In [16]:
import numpy as np

#create an array of strings
array1 = np.array(['hello','world'])

#join the string in the array using a dash as the delimiter
result = np.char.join('-',array1)

print(result)

['h-e-l-l-o' 'w-o-r-l-d']


In [17]:
import numpy as np

#crete two array of strings
array1 = np.array(['C','Python','Swift'])
array2 = np.array(['C','Python','java'])

#check if each element of array is equal
result = np.char.equal(array1,array2)

print(result)


[ True  True False]


In [18]:
#numpy broadcasting

import numpy as np

#create 1-D array
array1 = np.array([1,2,3])

#create 2-D array
array2 = np.array([[1],[2],[3]])

#add arrays of diferent dimension 
#size of array1 expands to match with array2

sum = array1+array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
#numpy matrix operations

functions -> description
array() -> create a matrix
dot() -> perform matrix multiplication
transpose() -> transpose a matrix
linalg.inv() -> calculates the inverse of matrix
linalg.det() -> calculaets the determinant of a matrix
flatten() -> transform a matrix into 1D array

In [20]:
import numpy as np

#create a 2X2 matrix
matrix1 = np.array([[1,3],
                   [5,7]])

print("2X2 matrix : \n",matrix1)

#create a 3X3 matrix
matrix2 = np.array([[2,3,5],
                   [7,14,21],
                   [1,3,5]])

print("\n 3X3 matrix :\n",matrix2)

2X2 matrix : 
 [[1 3]
 [5 7]]

 3X3 matrix :
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


In [21]:
import numpy as np

#creates two matrices
matrix1 = np.array([[1,3],
                   [5,7]])

matrix2 = np.array([[2,6],
                   [4,8]])

#calculate the dot product of the two matrices
result = np.dot(matrix1,matrix2)

print("matrix1 X matrix2: \n",result)

matrix1 X matrix2: 
 [[14 30]
 [38 86]]


In [22]:
np.multiply(matrix1,matrix2)

array([[ 2, 18],
       [20, 56]])

In [23]:
import numpy as np

#create a matrix
matrix1 = np.array([[1,3],[5,7]])

#get transpose of matrix1
result = np.transpose(matrix1)

print(result)


[[1 5]
 [3 7]]


In [27]:
import numpy as np

#create a 3X3 square matrix
matrix = np.array([[[1,3,5],[7,9,2],
                    [4,6,8]]])

#find inverse of matrix
result = np.linalg.inv(matrix1)

print(result)

[[-0.875  0.375]
 [ 0.625 -0.125]]


In [28]:
import numpy as np
 #create a matrix
matrix1 = np.array([[1,2,3],[4,5,1],[2,3,4]])

#find determinant of matrix1
result = np.linalg.det(matrix1)

print(result)

-4.999999999999999


In [29]:
#flattern matrix in numpy

import numpy as np

#create a 2X3 matrix
matrix1 = np.array([[1,2,3],[4,5,7]])
 
result = matrix1.flatten()
print("flattened 2X3 matrix:",result)


flattened 2X3 matrix: [1 2 3 4 5 7]


In [1]:
#numpy set operation

import numpy as np

A = np.array([1,2,3])
B = np.array([0,2,3])

#union of two array
result = np.union1d(A,B)

print(result)

[0 1 2 3]


In [2]:
import numpy as np

A = np.array([1,3,5])
B = np.array([0,2,3])

#intersection of two arrays
result = np.intersect1d(A,B)

print(result)

[3]


In [3]:
import numpy as np

A = np.array([1,3,5])
B = np.array([0,2,3])

#difference of two array
result = np.setdiff1d(A,B)

print(result)

[1 5]


In [4]:
import numpy as np

A = np.array([1,3,5])
B = np.array([0,2,3])

#symmetric difference of two array
result = np.setxor1d(A,B)

print(result)

[0 1 2 5]


In [5]:
import numpy as np

array1 = np.array([1,1,2,2,4,7,7,3,5,2,5])

#unique values from array
result = np.unique(array1)

print(result)

[1 2 3 4 5 7]


In [6]:
# numpy vectorization

import numpy as np

array1= np.array([1,2,3,4,5])
number = 10

#number sums up with each array element
result = array1+number

print(result)

[11 12 13 14 15]


In [7]:
import numpy as np

#define two 2D array
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[0,1,2],[0,1,2]])

#add two array (vectorization)
array_sum = array1 + array2

print(array_sum)

[[1 3 5]
 [4 6 8]]


In [11]:
import time

start  = time.time()

array1 = [1,2,3,4,5]

for i in range(len(array1)):
    array1[i] += 10
    
end = time.time()

print("for loop time:", end - start)

for loop time: 0.0


In [12]:
import time

start  = time.time()

array1 = [1,2,3,4,5]

for i in range(len(array1)):
    array1[i] += 10
    
end = time.time()           #time taken to execute for loop
print(end)

print("for loop time:", end - start)

1693992949.1246197
for loop time: 0.0


In [15]:
import numpy as np
import time

start  = time.time()

array1 = np.array([1,2,3,4,5])

result = array1 +10

end = time.time()

print("Vectorization time: ", end - start)

Vectorization time:  0.0


In [38]:
import numpy as np

#use datetime64() for different time units
year = np.datetime64('2023','Y')
month =  np.datetime64('2023-04','M')
day =  np.datetime64('2023-04-29','D')
hour =  np.datetime64('2023-04-29T10','h')
minute =  np.datetime64('2023-04-29T10:30','m')
seconds =  np.datetime64('2023-04-29T10:30:15','s')

print('year: ',year)
print('Month: ',month)
print('day: ',day)
print('hour: ',hour)
print('minute : ',minute)
print('seconds: ',seconds)


year:  2023
Month:  2023-04
day:  2023-04-29
hour:  2023-04-29T10
minute :  2023-04-29T10:30
seconds:  2023-04-29T10:30:15


In [18]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8])

#select a single element
simple_indexing = array1[3]

print("simple indexing: ",simple_indexing)

#select multple elements
fancy_indexing = array1[[1,2,5,7]]

print("fancy indexing: ",fancy_indexing)

simple indexing:  4
fancy indexing:  [2 3 6 8]


In [20]:
#numpy random

#random() function generates random floating numbers in the range of 0.1, and 1.0. It takes no parameters and returns values uniformly distributed between 0 and 1
# to do the experiment random is required
#uses in probablity 

import numpy as np

#generate random integer from 0 to  9
random_number = np.random.randint(0,10)      #randint -> random integer

print(random_number)

8


In [21]:
from numpy import random

random_number = random.randint(0,10)

print(random_number)

3


In [22]:
import numpy as np

#generate random float-point number between 0 and 1
random_number = np.random.rand()     #random.rand() -> indicates floating value  #random.randint() -> indicates integer value

print(random_number)



0.8974201425463126


In [25]:
import numpy as np

#generate 1D array of 5 random integer between 0 and 9
integer_array = np.random.randint(0,10,5)      #here 5 indicates the 5 random values have been given

print("1D Random Integer array: \n",integer_array)

#generate 1D of 5 random number betwwen 0 and 1
float_array = np.random.rand(5)

print("\n 1D random float array: \n",float_array)

#generate 2D array of shape (3,4) with random integer
result = np.random.randint(0,10,(3,4))       #(3,4) indicates the size of matrix

print("\n 2D random integer array: \n", result)

1D Random Integer array: 
 [5 6 3 5 2]

 1D random float array: 
 [0.02335118 0.09145114 0.61397353 0.22822656 0.06342988]

 2D random integer array: 
 [[9 7 6 7]
 [7 5 5 7]
 [1 3 6 3]]


In [26]:
# choice function in numpy
#used in ludo and many games

import numpy as np

#create an array of integer from 1 to 5
array1 = np.array([1,2,3,4,5])

#choose a random number from array
random_choice = np.random.choice(array1)

print(random_choice)

3


 numpy linear algebra functions

operators -> description
dot() -> calculates product of two array
inner() -> calculates inner product of array
outer() -> calculates outer product of atrray
det() -> calculates deteminant of a matrix
solve() -> solves linear matrix equation
inv() ->calulates the multiplicative inverse of the matrix
trace() -> calculate the sum of digonal elements

In [28]:
import numpy as np

array1 = np.array([1,3,5])
array2 = np.array([2,4,6])

#use of dot() to perform array multiplication
result = np.dot(array1,array2)

print(result)

44


In [31]:
import numpy as np

array1 = np.array([[1,3],
                   [5,7]])
array2 = np.array([[2,4],
                   [6,8]])

#use of inner() for 2D array
result = np.inner(array1,array2)

print(result)

[[14 30]
 [38 86]]


In [32]:
import numpy as np

array1 = np.array([1,3,5])
array2 = np.array([2,4,6])

#use of outer() to perfom outer multiplication
result = np.outer(array1,array2)

print(result)

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


In [33]:
import numpy as np

#define a square matrix
array1 = np.array([[1,3],
                   [5,7]])

#compute the determinant of array 1
result = np.linalg.det(array1)
                   
print(result)

-7.999999999999998


In [35]:
import numpy as np

#define the coefficient matrix A
A = np.array([[2,4],
                [6,8]])
    
#define the constant vector b
b= np.array([5,6])

#solve the system of linear equation Ax = b
x = np.linalg.solve(A,b)

print(x)

[-2.    2.25]


In [36]:
import numpy as np

#define a 2X2 matrix
array1 = np.array([[2,4],
                [6,8]])

#compute the inverse of  matrix
result = np.linalg.inv(array1)

print(result)
    

[[-1.    0.5 ]
 [ 0.75 -0.25]]


In [37]:
import numpy as np

#define a 3X3 matrix
array1 = np.array([[6,3,5],
                [9,2,1],
                  [7,8,4]])

#compute the trace of  matrix
result = np.trace(array1)

print(result)
    

12
